### ISSUE TITLE
Propose to cleanup of client-features folder

### ISSUE THREAD

**Issue by TRJensen** [tpm-rs/tpm-rs#103]
The client-features folder contains a single wrapper function `get_manufacturer_id`, which creates a `GetCapabilityCmd` struct and sends the request via `run_command`.

Based on discussions in https://github.com/tpm-rs/tpm-rs/pull/63, we should avoid having function wrappers for TPM api interface, and instead let user create create the Cmd structure, and call the run_command() - or run_command_with_handles().

I would suggest to:
- Remove "client-features" folder (incl get_manufacturer_id function).
- Adapt and move test vectors to the client folder.

**Comment by trent-reed** [comment]
Thanks!

I'm actually not opposed to something like `client-features`, but I think it needs more design work. My understanding is that `client` is a raw client to communicate with the TPM, and `client-features` is supposed to be a wrapper over a raw client that makes certain operations simpler (such as, in this case, getting the manufacturer ID).

I'm not opposed to having such an abstraction, I just don't think it should be raw functions. It needs a bit more design (maybe just having a `struct TpmFeatureClient(TpmClient);` and implementing functions on that is enough).

---

Anyways, I do think it's probably worth focusing on `TpmClient` first, *then* working on the feature client. But if we want to keep `client-features` around, we should make it more of a structured type or something, and less of just floating functions.
