### ISSUE TITLE
"Project" is not visible

### ISSUE THREAD

**Issue by onkoe** [tpm-rs/tpm-rs#117]
Hey there! Thanks for the useful crate! I was hoping to get a better view of what's implemented, but the README's link to the GitHub Projects board appears to be non-existent.

I think it's probably private by mistake. 

Could someone with org access please take a look?

**Comment by oddcoder** [comment]
We mainly use the [issues](https://github.com/tpm-rs/tpm-rs/issues) for code related discussions and [discussions](https://github.com/orgs/tpm-rs/discussions) for other discussions that not code related but still related to tpm-rs.
I would update the readme shortly.

That repository is private, but no one uses it for anything, should be ideally deleted.
