### ISSUE TITLE
Add TPM_GetRandom Command on client side.

### ISSUE THREAD

**Issue by oddcoder** [tpm-rs/tpm-rs#118]
That should be implemented somewhere at [base/src/commands.rs](https://github.com/tpm-rs/tpm-rs/blob/main/base/src/commands.rs).

The implementation should be straight forward usage of `TpmCommand` similar to the rest of the file.

**Comment by oddcoder** [comment]
@TRJensen would you be interested in this ?

**Comment by TRJensen** [comment]
Yes - just assigned myself :-)
