### ISSUE TITLE
Enable Commit based (rebase + merge/fast forward) for pull requests

### ISSUE THREAD

**Issue by oddcoder** [tpm-rs/tpm-rs#66]
@chrisfenner Apparently this is disabled (or was disabled last time I checked) for this project. The only way to merge was squash all commits into one.

Bu there are some merits in leaving them separately. Sometimes I find myself having to do some refactoring before I do real work. It will be hard to justify the refactoring if submitted alone, but it will also be not a good idea to squash the refactoring with the real modifications when sending both as single pull request.

What do you think?

**Comment by chrisfenner** [comment]
I'm mildly in support of squashing all the time but I totally get the use-case you just described @oddcoder ! @bradlitterell @esmusick @jettr what do y'all think about it?

**Comment by esmusick** [comment]
I pretty much always prefer squashing, but am OK with leaving the option open in limited cases with reasonable justification. That's definitely harder to enforce, but we could try making a point to call it out in all reviews to try to establish a norm.

**Comment by chrisfenner** [comment]
As an experiment, I've enabled rebases in the settings :)

**Comment by oddcoder** [comment]
Personally, I am more used to commit based work flow, where each commit in the whole PR does one thing but the PR works toward one goal. I will still keep the pull requests short, Thanks a lot.

**Comment by jettr** [comment]
> That's definitely harder to enforce, but we could try making a point to call it out in all reviews to try to establish a norm.

If we open it up, it will definitely be more difficult to enforce consistency.

A rebase merge still leave a clean commit history, which is good. What is the review flow like though when an author needs to update code from a commit. Does the author need to force push? It would be really nice if we could avoid force pushing. I might be missing something though.

**Comment by oddcoder** [comment]
I am not entirely sure I understand what you mean by force push. If you mean force pushing in the developer's own branch, then I imagine yes. I actually did that in my previous pull requests here. But I tend to think of it as sending new patch set rather than force pushing. If you to mean force pushing to main, then no. Just as with squashing

**Comment by chrisfenner** [comment]
Yeah, now the choices for maintainers when merging become:

* Ignore how many commits the PR sender has. Just squash and merge
* Check that the PR consists of a few well-organized commits (usually this requires the PR sender to force-push their branch, to incorporate feedback without just adding more commits). Then rebase instead of squash.

**Comment by jettr** [comment]
> If you mean force pushing in the developer's own branch, then I imagine yes. I actually did that in my previous pull requests here. But I tend to think of it as sending new patch set rather than force pushing

Correct, I am thinking about having to force push to the under-review branch during the review. So far I haven't seen good tooling or handling when force pushing during a PR. There isn't a good way to see difference between the old set of commits and the new set. It also seems like the old SHA gets cleaned up at some and you lose review history. Also it is more difficult to see what changed from "patch set" to "patch set" based on reviewer feedback.

After looking at different options and discussing with various people about good github merge strategies, it seems like using a PR as a single commit or CL is a good mental model, and each commit within the PR is like a patchset in response to reviewer feedback. With that model, developers don't have to force push their dev branch, and reviewers can easily see difference between patchset. The commit descriptions for each of the "fixup"/patchset commits don't actually matter that much either as they won't make it to the main branch as is. The revision history (the various changes during the review) of the PR is also maintained long term.
